// Static metadata for all 114 surahs — avoids 114 API calls on the home page.
// Sourced from the Quran; this data is stable and does not need dynamic fetching.

export const SURAHS = [
  { number: 1,   name: 'Al-Fatihah',     arabic: 'الفاتحة',    translation: 'The Opening',              verses: 7,   revelation: 'Makkah'  },
  { number: 2,   name: 'Al-Baqarah',     arabic: 'البقرة',     translation: 'The Cow',                  verses: 286, revelation: 'Madinah' },
  { number: 3,   name: "Aal-E-Imran",    arabic: 'آل عمران',   translation: 'Family of Imran',          verses: 200, revelation: 'Madinah' },
  { number: 4,   name: "An-Nisa",        arabic: 'النساء',     translation: 'The Women',                verses: 176, revelation: 'Madinah' },
  { number: 5,   name: "Al-Ma'idah",     arabic: 'المائدة',    translation: 'The Table Spread',         verses: 120, revelation: 'Madinah' },
  { number: 6,   name: "Al-An'am",       arabic: 'الأنعام',    translation: 'The Cattle',               verses: 165, revelation: 'Makkah'  },
  { number: 7,   name: "Al-A'raf",       arabic: 'الأعراف',    translation: 'The Heights',              verses: 206, revelation: 'Makkah'  },
  { number: 8,   name: 'Al-Anfal',       arabic: 'الأنفال',    translation: 'The Spoils of War',        verses: 75,  revelation: 'Madinah' },
  { number: 9,   name: 'At-Tawbah',      arabic: 'التوبة',     translation: 'The Repentance',           verses: 129, revelation: 'Madinah' },
  { number: 10,  name: 'Yunus',          arabic: 'يونس',       translation: 'Jonah',                    verses: 109, revelation: 'Makkah'  },
  { number: 11,  name: 'Hud',            arabic: 'هود',        translation: 'Hud',                      verses: 123, revelation: 'Makkah'  },
  { number: 12,  name: 'Yusuf',          arabic: 'يوسف',       translation: 'Joseph',                   verses: 111, revelation: 'Makkah'  },
  { number: 13,  name: "Ar-Ra'd",        arabic: 'الرعد',      translation: 'The Thunder',              verses: 43,  revelation: 'Madinah' },
  { number: 14,  name: 'Ibrahim',        arabic: 'إبراهيم',    translation: 'Abraham',                  verses: 52,  revelation: 'Makkah'  },
  { number: 15,  name: 'Al-Hijr',        arabic: 'الحجر',      translation: 'The Rocky Tract',          verses: 99,  revelation: 'Makkah'  },
  { number: 16,  name: 'An-Nahl',        arabic: 'النحل',      translation: 'The Bee',                  verses: 128, revelation: 'Makkah'  },
  { number: 17,  name: "Al-Isra",        arabic: 'الإسراء',    translation: 'The Night Journey',        verses: 111, revelation: 'Makkah'  },
  { number: 18,  name: 'Al-Kahf',        arabic: 'الكهف',      translation: 'The Cave',                 verses: 110, revelation: 'Makkah'  },
  { number: 19,  name: 'Maryam',         arabic: 'مريم',       translation: 'Mary',                     verses: 98,  revelation: 'Makkah'  },
  { number: 20,  name: 'Ta-Ha',          arabic: 'طه',         translation: 'Ta-Ha',                    verses: 135, revelation: 'Makkah'  },
  { number: 21,  name: "Al-Anbiya",      arabic: 'الأنبياء',   translation: 'The Prophets',             verses: 112, revelation: 'Makkah'  },
  { number: 22,  name: 'Al-Hajj',        arabic: 'الحج',       translation: 'The Pilgrimage',           verses: 78,  revelation: 'Madinah' },
  { number: 23,  name: "Al-Mu'minun",    arabic: 'المؤمنون',   translation: 'The Believers',            verses: 118, revelation: 'Makkah'  },
  { number: 24,  name: 'An-Nur',         arabic: 'النور',      translation: 'The Light',                verses: 64,  revelation: 'Madinah' },
  { number: 25,  name: 'Al-Furqan',      arabic: 'الفرقان',    translation: 'The Criterion',            verses: 77,  revelation: 'Makkah'  },
  { number: 26,  name: "Ash-Shu'ara",    arabic: 'الشعراء',    translation: 'The Poets',                verses: 227, revelation: 'Makkah'  },
  { number: 27,  name: 'An-Naml',        arabic: 'النمل',      translation: 'The Ant',                  verses: 93,  revelation: 'Makkah'  },
  { number: 28,  name: 'Al-Qasas',       arabic: 'القصص',      translation: 'The Stories',              verses: 88,  revelation: 'Makkah'  },
  { number: 29,  name: 'Al-Ankabut',     arabic: 'العنكبوت',   translation: 'The Spider',               verses: 69,  revelation: 'Makkah'  },
  { number: 30,  name: 'Ar-Rum',         arabic: 'الروم',      translation: 'The Romans',               verses: 60,  revelation: 'Makkah'  },
  { number: 31,  name: 'Luqman',         arabic: 'لقمان',      translation: 'Luqman',                   verses: 34,  revelation: 'Makkah'  },
  { number: 32,  name: 'As-Sajdah',      arabic: 'السجدة',     translation: 'The Prostration',          verses: 30,  revelation: 'Makkah'  },
  { number: 33,  name: 'Al-Ahzab',       arabic: 'الأحزاب',    translation: 'The Combined Forces',      verses: 73,  revelation: 'Madinah' },
  { number: 34,  name: 'Saba',           arabic: 'سبأ',        translation: 'Sheba',                    verses: 54,  revelation: 'Makkah'  },
  { number: 35,  name: 'Fatir',          arabic: 'فاطر',       translation: 'Originator',               verses: 45,  revelation: 'Makkah'  },
  { number: 36,  name: 'Ya-Sin',         arabic: 'يس',         translation: 'Ya Sin',                   verses: 83,  revelation: 'Makkah'  },
  { number: 37,  name: 'As-Saffat',      arabic: 'الصافات',    translation: 'Those Who Set the Ranks',  verses: 182, revelation: 'Makkah'  },
  { number: 38,  name: 'Sad',            arabic: 'ص',          translation: 'The Letter Sad',           verses: 88,  revelation: 'Makkah'  },
  { number: 39,  name: 'Az-Zumar',       arabic: 'الزمر',      translation: 'The Troops',               verses: 75,  revelation: 'Makkah'  },
  { number: 40,  name: 'Ghafir',         arabic: 'غافر',       translation: 'The Forgiver',             verses: 85,  revelation: 'Makkah'  },
  { number: 41,  name: 'Fussilat',       arabic: 'فصلت',       translation: 'Explained in Detail',      verses: 54,  revelation: 'Makkah'  },
  { number: 42,  name: 'Ash-Shura',      arabic: 'الشورى',     translation: 'The Consultation',         verses: 53,  revelation: 'Makkah'  },
  { number: 43,  name: 'Az-Zukhruf',     arabic: 'الزخرف',     translation: 'The Ornaments of Gold',    verses: 89,  revelation: 'Makkah'  },
  { number: 44,  name: 'Ad-Dukhan',      arabic: 'الدخان',     translation: 'The Smoke',                verses: 59,  revelation: 'Makkah'  },
  { number: 45,  name: 'Al-Jathiyah',    arabic: 'الجاثية',    translation: 'The Crouching',            verses: 37,  revelation: 'Makkah'  },
  { number: 46,  name: 'Al-Ahqaf',       arabic: 'الأحقاف',    translation: 'The Wind-Curved Sandhills',verses: 35,  revelation: 'Makkah'  },
  { number: 47,  name: 'Muhammad',       arabic: 'محمد',       translation: 'Muhammad',                 verses: 38,  revelation: 'Madinah' },
  { number: 48,  name: 'Al-Fath',        arabic: 'الفتح',      translation: 'The Victory',              verses: 29,  revelation: 'Madinah' },
  { number: 49,  name: 'Al-Hujurat',     arabic: 'الحجرات',    translation: 'The Rooms',                verses: 18,  revelation: 'Madinah' },
  { number: 50,  name: 'Qaf',            arabic: 'ق',          translation: 'The Letter Qaf',           verses: 45,  revelation: 'Makkah'  },
  { number: 51,  name: 'Adh-Dhariyat',   arabic: 'الذاريات',   translation: 'The Winnowing Winds',      verses: 60,  revelation: 'Makkah'  },
  { number: 52,  name: 'At-Tur',         arabic: 'الطور',      translation: 'The Mount',                verses: 49,  revelation: 'Makkah'  },
  { number: 53,  name: 'An-Najm',        arabic: 'النجم',      translation: 'The Star',                 verses: 62,  revelation: 'Makkah'  },
  { number: 54,  name: 'Al-Qamar',       arabic: 'القمر',      translation: 'The Moon',                 verses: 55,  revelation: 'Makkah'  },
  { number: 55,  name: 'Ar-Rahman',      arabic: 'الرحمن',     translation: 'The Beneficent',           verses: 78,  revelation: 'Madinah' },
  { number: 56,  name: "Al-Waqi'ah",     arabic: 'الواقعة',    translation: 'The Inevitable',           verses: 96,  revelation: 'Makkah'  },
  { number: 57,  name: 'Al-Hadid',       arabic: 'الحديد',     translation: 'The Iron',                 verses: 29,  revelation: 'Madinah' },
  { number: 58,  name: 'Al-Mujadila',    arabic: 'المجادلة',   translation: 'The Pleading Woman',       verses: 22,  revelation: 'Madinah' },
  { number: 59,  name: 'Al-Hashr',       arabic: 'الحشر',      translation: 'The Exile',                verses: 24,  revelation: 'Madinah' },
  { number: 60,  name: 'Al-Mumtahanah',  arabic: 'الممتحنة',   translation: 'She That is to be Examined',verses: 13, revelation: 'Madinah' },
  { number: 61,  name: 'As-Saf',         arabic: 'الصف',       translation: 'The Ranks',                verses: 14,  revelation: 'Madinah' },
  { number: 62,  name: "Al-Jumu'ah",     arabic: 'الجمعة',     translation: 'The Congregation Friday',  verses: 11,  revelation: 'Madinah' },
  { number: 63,  name: 'Al-Munafiqun',   arabic: 'المنافقون',  translation: 'The Hypocrites',           verses: 11,  revelation: 'Madinah' },
  { number: 64,  name: 'At-Taghabun',    arabic: 'التغابن',    translation: 'The Mutual Disillusion',   verses: 18,  revelation: 'Madinah' },
  { number: 65,  name: 'At-Talaq',       arabic: 'الطلاق',     translation: 'The Divorce',              verses: 12,  revelation: 'Madinah' },
  { number: 66,  name: 'At-Tahrim',      arabic: 'التحريم',    translation: 'The Prohibition',          verses: 12,  revelation: 'Madinah' },
  { number: 67,  name: 'Al-Mulk',        arabic: 'الملك',      translation: 'The Sovereignty',          verses: 30,  revelation: 'Makkah'  },
  { number: 68,  name: 'Al-Qalam',       arabic: 'القلم',      translation: 'The Pen',                  verses: 52,  revelation: 'Makkah'  },
  { number: 69,  name: "Al-Haqqah",      arabic: 'الحاقة',     translation: 'The Reality',              verses: 52,  revelation: 'Makkah'  },
  { number: 70,  name: "Al-Ma'arij",     arabic: 'المعارج',    translation: 'The Ascending Stairways',  verses: 44,  revelation: 'Makkah'  },
  { number: 71,  name: 'Nuh',            arabic: 'نوح',        translation: 'Noah',                     verses: 28,  revelation: 'Makkah'  },
  { number: 72,  name: 'Al-Jinn',        arabic: 'الجن',       translation: 'The Jinn',                 verses: 28,  revelation: 'Makkah'  },
  { number: 73,  name: 'Al-Muzzammil',   arabic: 'المزمل',     translation: 'The Enshrouded One',       verses: 20,  revelation: 'Makkah'  },
  { number: 74,  name: 'Al-Muddaththir', arabic: 'المدثر',     translation: 'The Cloaked One',          verses: 56,  revelation: 'Makkah'  },
  { number: 75,  name: 'Al-Qiyamah',     arabic: 'القيامة',    translation: 'The Resurrection',         verses: 40,  revelation: 'Makkah'  },
  { number: 76,  name: 'Al-Insan',       arabic: 'الإنسان',    translation: 'The Human',                verses: 31,  revelation: 'Madinah' },
  { number: 77,  name: 'Al-Mursalat',    arabic: 'المرسلات',   translation: 'The Emissaries',           verses: 50,  revelation: 'Makkah'  },
  { number: 78,  name: "An-Naba",        arabic: 'النبأ',      translation: 'The Tidings',              verses: 40,  revelation: 'Makkah'  },
  { number: 79,  name: "An-Nazi'at",     arabic: 'النازعات',   translation: 'Those Who Drag Forth',     verses: 46,  revelation: 'Makkah'  },
  { number: 80,  name: 'Abasa',          arabic: 'عبس',        translation: 'He Frowned',               verses: 42,  revelation: 'Makkah'  },
  { number: 81,  name: 'At-Takwir',      arabic: 'التكوير',    translation: 'The Overthrowing',         verses: 29,  revelation: 'Makkah'  },
  { number: 82,  name: 'Al-Infitar',     arabic: 'الانفطار',   translation: 'The Cleaving',             verses: 19,  revelation: 'Makkah'  },
  { number: 83,  name: 'Al-Mutaffifin',  arabic: 'المطففين',   translation: 'The Defrauding',           verses: 36,  revelation: 'Makkah'  },
  { number: 84,  name: 'Al-Inshiqaq',    arabic: 'الانشقاق',   translation: 'The Sundering',            verses: 25,  revelation: 'Makkah'  },
  { number: 85,  name: 'Al-Buruj',       arabic: 'البروج',     translation: 'The Mansions of the Stars',verses: 22,  revelation: 'Makkah'  },
  { number: 86,  name: 'At-Tariq',       arabic: 'الطارق',     translation: 'The Morning Star',         verses: 17,  revelation: 'Makkah'  },
  { number: 87,  name: "Al-A'la",        arabic: 'الأعلى',     translation: 'The Most High',            verses: 19,  revelation: 'Makkah'  },
  { number: 88,  name: 'Al-Ghashiyah',   arabic: 'الغاشية',    translation: 'The Overwhelming',         verses: 26,  revelation: 'Makkah'  },
  { number: 89,  name: 'Al-Fajr',        arabic: 'الفجر',      translation: 'The Dawn',                 verses: 30,  revelation: 'Makkah'  },
  { number: 90,  name: 'Al-Balad',       arabic: 'البلد',      translation: 'The City',                 verses: 20,  revelation: 'Makkah'  },
  { number: 91,  name: 'Ash-Shams',      arabic: 'الشمس',      translation: 'The Sun',                  verses: 15,  revelation: 'Makkah'  },
  { number: 92,  name: 'Al-Layl',        arabic: 'الليل',      translation: 'The Night',                verses: 21,  revelation: 'Makkah'  },
  { number: 93,  name: 'Ad-Duha',        arabic: 'الضحى',      translation: 'The Morning Hours',        verses: 11,  revelation: 'Makkah'  },
  { number: 94,  name: 'Ash-Sharh',      arabic: 'الشرح',      translation: 'The Relief',               verses: 8,   revelation: 'Makkah'  },
  { number: 95,  name: 'At-Tin',         arabic: 'التين',      translation: 'The Fig',                  verses: 8,   revelation: 'Makkah'  },
  { number: 96,  name: 'Al-Alaq',        arabic: 'العلق',      translation: 'The Clot',                 verses: 19,  revelation: 'Makkah'  },
  { number: 97,  name: 'Al-Qadr',        arabic: 'القدر',      translation: 'The Power',                verses: 5,   revelation: 'Makkah'  },
  { number: 98,  name: 'Al-Bayyinah',    arabic: 'البينة',     translation: 'The Clear Proof',          verses: 8,   revelation: 'Madinah' },
  { number: 99,  name: 'Az-Zalzalah',    arabic: 'الزلزلة',    translation: 'The Earthquake',           verses: 8,   revelation: 'Madinah' },
  { number: 100, name: 'Al-Adiyat',      arabic: 'العاديات',   translation: 'The Courser',              verses: 11,  revelation: 'Makkah'  },
  { number: 101, name: "Al-Qari'ah",     arabic: 'القارعة',    translation: 'The Calamity',             verses: 11,  revelation: 'Makkah'  },
  { number: 102, name: 'At-Takathur',    arabic: 'التكاثر',    translation: 'Rivalry in World Increase',verses: 8,   revelation: 'Makkah'  },
  { number: 103, name: 'Al-Asr',         arabic: 'العصر',      translation: 'The Declining Day',        verses: 3,   revelation: 'Makkah'  },
  { number: 104, name: 'Al-Humazah',     arabic: 'الهمزة',     translation: 'The Traducer',             verses: 9,   revelation: 'Makkah'  },
  { number: 105, name: 'Al-Fil',         arabic: 'الفيل',      translation: 'The Elephant',             verses: 5,   revelation: 'Makkah'  },
  { number: 106, name: 'Quraysh',        arabic: 'قريش',       translation: 'Quraysh',                  verses: 4,   revelation: 'Makkah'  },
  { number: 107, name: "Al-Ma'un",       arabic: 'الماعون',    translation: 'The Small Kindnesses',     verses: 7,   revelation: 'Makkah'  },
  { number: 108, name: 'Al-Kawthar',     arabic: 'الكوثر',     translation: 'The Abundance',            verses: 3,   revelation: 'Makkah'  },
  { number: 109, name: 'Al-Kafirun',     arabic: 'الكافرون',   translation: 'The Disbelievers',         verses: 6,   revelation: 'Makkah'  },
  { number: 110, name: 'An-Nasr',        arabic: 'النصر',      translation: 'The Divine Support',       verses: 3,   revelation: 'Madinah' },
  { number: 111, name: 'Al-Masad',       arabic: 'المسد',      translation: 'The Palm Fibre',           verses: 5,   revelation: 'Makkah'  },
  { number: 112, name: 'Al-Ikhlas',      arabic: 'الإخلاص',    translation: 'The Sincerity',            verses: 4,   revelation: 'Makkah'  },
  { number: 113, name: 'Al-Falaq',       arabic: 'الفلق',      translation: 'The Daybreak',             verses: 5,   revelation: 'Makkah'  },
  { number: 114, name: 'An-Nas',         arabic: 'الناس',      translation: 'The Mankind',              verses: 6,   revelation: 'Makkah'  },
];

export function getSurahByNumber(n) {
  return SURAHS.find((s) => s.number === Number(n)) ?? null;
}

export function searchSurahs(query) {
  const q = query.toLowerCase().trim();
  if (!q) return SURAHS;
  return SURAHS.filter(
    (s) =>
      s.name.toLowerCase().includes(q) ||
      s.arabic.includes(q) ||
      s.translation.toLowerCase().includes(q) ||
      String(s.number).includes(q),
  );
}
